# Site settings
title: Tom Jose's Resume 
description: Tom's CV
favicon: /assets/img/avatar.jpg
baseurl: https://tomchoondal.github.io/resume
url: https://tomchoondal.github.io/resume
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Tom Jose C
  title: Senior UX Developer
  address: Cochin, India
  email: tomjosec@gmail.com
  link: http://tomchoondal.us
  weibo:
  github: tomchoondal
  linkedin: tom-jose-73a66557
  gavatar: /resume/assets/img/avatar.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Valorem Private Limited
      location: Cochin, India
      title: Senior UX Developer
      started: 2016
      duration: (2016 - Present)
      description: Senior UX Developer working with User Experience team of valorem
    - work2:
      company: IdentityMine Software Solutions (India) Limited
      location: Cochin, India
      title: UX Developer
      started: 2013
      duration: (2013 - 2016)
      description:

  educationHistory:
    - education1:
      organization: Jyothi  Engineering College, Thrissur
      location: Cheruthuruthy Kerala, India
      degree: Bachelor
      major: Computer Science and Engineering
      started: 2008
      duration: (2008 - 2012)
      description: 
  languages:
    - language1:
      name: Malayalam
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: C#.Net
      percentage: 80%
    - skill2:
      name: PhotoShop
      percentage: 60%
    - skill3:
      name: Xamarin iOs UI
      percentage: 75%
    - skill4:
      name: XAML
      percentage: 95%
    - skill5:
      name: WPF
      percentage: 90%
    - skill6:
      name: Xamarin Android UI
      percentage: 70%
    - skill7:
      name: UWP
      percentage: 80%
